#include <Solution.h>

int main(void) {
	string input = "jvgegcvhehzqdmlzaoqblsawjpdjepqvbsrqmzcqwreewdtrnxlxshbevyorswlhdcjyzvibsmvwgdwmdqmwvyciuqwtlnbtgvkufeolzpzrbfoztyceeqyywnzwecvpetzjdnfmpykbonrjltnbbtxbtqwlbtrskceoyupjidhoxqmysnjgaprphmygbfqbbgamgyrgudqxwakkwoanxcuehdcxeaiphhdfrloqbcayiewxjpogvssnwsycrutxvbuaegycgvugmygumzsbnusdqmejuicnmsfkhyatexynibiymmtvniyntjyluiqspoazlvoxbljmohehunujwxihohdsvkrhdmhiiwmdumduypvejlkpzqceytefuxihesnwiyvbddploxijffrxmwlqenrfjiobfvoxtnsiigxvmuhbohreykexcgjmnakenfrsjpxsyrvdsekhuhrgtqiyrsfhfntotxrgqqqoztpqyiyldcciskddtfobgwwsdfgmabxwopysavjvoqrkzbenespibdjkfmxevwzqevjudskxxvdinfvrmqgyxcjhxqevcablajybbtkxyorqwsfbykvhnoixkttjxtuinecsyforvouddwhzpqmttojjekthgbhihutqoisdrdbejnhxfgawtttjhqtncnbuxpocuepzhxgrsfkdtbrpfsljxpwhhqcjjwblzdzscdbbvugphijyzeoctjzydfvsniuigepssdcofrrkfuhejgeorjrmremudqxkclicyhiwqhwnwhlxjseuandmvnithfudpbpjkdeieyuywwqosodytfahsrqmpoalgaszbhhrlvtjwjigjdcpbnveapgdpsjvqwydussnpgwydhuqibosxbgyhaiilxhabftgjxvocoajqqfgrtkkmtfevwmeerihwmmql";
	Solution *test = new Solution();
	cout << test->longestDupSubstring(input) << endl;
	return 0;
}
